### ISSUE TITLE
Use parallel=True by default can be problematic in multiprocessing applications

### ISSUE THREAD

**Issue by riqiang-dp** [bmcfee/resampy#107]
In my use case an update from resampy 0.2.2 to 0.3.1 broke my program, since resampy is called in a multiprocessing pool. Depending on the version of other packages (I didn't find out the exact reason for the different following behavior), this would either end up making the program really slow (because n_cpu * n_cpu number of processes were created by calling multiprocessing inside multiprocessing), or emit this error:
`Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.`

Can you guys set it to False by default or give some warning about running resampy in multiprocessing scenario?

**Comment by bmcfee** [comment]
Thanks for raising this - can you provide a bit more context about how you're using the library? (I.e., are you calling it directly, or through some other package?)  Would it be easy to just add `parallel=False` to your call site?

I don't think a warning is necessarily appropriate, but we can certainly consider reverting the default back to parallel=False.  The thinking here was that multiprocessing applications like yours are probably not the default / most common setting, but we do want to make it easy to limit multi-core usage for exactly this kind of application.

It does sound like for your application, it would actually make a lot of sense to limit numba core usage globally (and not just for resampy) - that way it would apply to all numba-parallel usage and not just our package.  This can be done through a global environment variable as noted in #106 .

**Comment by riqiang-dp** [comment]
Thanks for the quick reply! 
So yes, if there's a way to auto-detect being in a subprocess, and disable it accordingly, that would also be great. 

Looking at #106, I think what they are seeing is this exact same problem.

I'll test `numba.set_num_threads(1)` to see if it works as well.

**Comment by riqiang-dp** [comment]
Ah it doesn't work unfortunately. That line effectively sets numba threads to 1, but I still got this error: `Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.`
I'm guessing it's because numba will still try to spawn the processes even though num_threads is set to one? I don't know, this is really outside of my domain haha.

**Comment by bmcfee** [comment]
That's a bummer, but good to know!  To the previous question: are you able to call resampy directly with parallel=False?  That will force it to use the single-threaded implementation, and should also fix it for you.  The catch here is that if you're using resampy through an intermediate library (eg librosa) the API isn't directly exposed yet.

**Comment by zhangrui-wolf** [comment]
We had the same problem with librosa. It was finally traced to a problem with the dependency package resampy. I'm here to leave a comment. The easiest way to reproduce this is to use the multiprocessing library and run it in parallel.

**Comment by talhaanwarch** [comment]
Have same issue with huggingface https://github.com/huggingface/datasets/issues/4820
