### ISSUE TITLE
Installation error - interp.c

### ISSUE THREAD

**Issue by orchidas** [bmcfee/resampy#22]
I've been trying to install librosa, as a result of which I had to get resampy. Whether I use pip to install librosa or resampy, or I use Cython after cloning resampy, I get the following error:

```
Error compiling Cython file:
------------------------------------------------------------
...
from cython cimport floating


@cython.boundscheck(False)
@cython.wraparound(False)
cpdef void resample_f(floating[:, :] x, floating[:, :] y,
     ^
------------------------------------------------------------

resampy\interp.pyx:15:6: Cannot convert 'void' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
from cython cimport floating


@cython.boundscheck(False)
@cython.wraparound(False)
cpdef void resample_f(floating[:, :] x, floating[:, :] y,
     ^
------------------------------------------------------------

resampy\interp.pyx:15:6: Cannot convert 'void' to Python object
building 'resampy.interp' extension
creating build\temp.win-amd64-2.7
creating build\temp.win-amd64-2.7\Release
creating build\temp.win-amd64-2.7\Release\resampy
C:\Program Files\MinGW\bin\gcc.exe -DMS_WIN64 -mdll -O -Wall -IC:\Users\ORCHISAMA\Anaconda\lib\site-packages\numpy\core\include -IC:
\Users\ORCHISAMA\Anaconda\include -IC:\Users\ORCHISAMA\Anaconda\PC -c resampy\interp.c -o build\temp.win-amd64-2.7\Release\resampy\i
nterp.o
resampy\interp.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
error: command 'C:\\Program Files\\MinGW\\bin\\gcc.exe' failed with exit status 1

```
Please help me out.

**Comment by bmcfee** [comment]
Thanks for the report.

Can you include version numbers for resampy (that you're trying to install) and cython?

**Comment by orchidas** [comment]
Thanks for your response. I have Cython 0.21 and I cloned the latest repository of resampy (0.1.2), so I am guessing that is up-to-date.

**Comment by bmcfee** [comment]
What happens if you try removing `resampy/interp.c` and rebuilding from scratch?

**Comment by bmcfee** [comment]
Aha!  It looks like you might need to upgrade cython.  Apparently support for `cpdef void` wasn't added until [0.24](https://github.com/cython/cython/commit/7df9d654b3e6c3d5812a95904872d35a3c94ef77).

If you can verify this, I'll update the requirements and push out a minor release.

**Comment by orchidas** [comment]
Sorry for the late reply. I tried updating Cython to version 0.24. It still doesn't work. I get these warnings followed by a bunch of 'undefined reference to' error messages.
```
`ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0x347): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0x37c): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0x5f9): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0x652): more undefined refe

ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xc6a): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xc7a): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xd17): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xd52): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xd76): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xd9d): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xdcd): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xdd8): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xdf2): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xe0a): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xe15): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xe83): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xe9b): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xea6): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xeb2): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xf10): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xf28): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xf33): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xf3f): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xfa4): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xfaf): undefined reference
ld\temp.win-amd64-2.7\Release\resampy\interp.o:interp.c:(.text+0xfcc): undefined reference`

```
Btw, I am running Python 2.7 with Anaconda on Win-64. Do I need to upgrade Python?

**Comment by bmcfee** [comment]
> I tried updating Cython to version 0.24. It still doesn't work.

Thanks for trying that out.  To be clear: is this still from the git clone, or a pip install?



> Btw, I am running Python 2.7 with Anaconda on Win-64. Do I need to upgrade Python?

You shouldn't -- everything is compatible with 2.7.  I don't have access to a windows system for development though, so apologies for not having tested thoroughly there.

**Comment by orchidas** [comment]
Both git clone and pip install give the same errors. It's probably a windows error then. Thanks anyway.

**Comment by bmcfee** [comment]
Well, we've at least moved up from "compiler error" to "linker error", so that's progress!

What compiler (+versions) are you using?  It would be helpful to have your environment documented here in case someone else comes across the same issue.

**Comment by orchidas** [comment]
Yes the .o linker file seems to be the problem. I am using GCC (MinGW) version 4.7.1.

**Comment by bmcfee** [comment]
[This post](http://stackoverflow.com/questions/32440789/compiling-cython-with-mingw-undefined-reference-pyexc) looks like it might be relevant for you.  So does [this one](http://stackoverflow.com/questions/6982009/cython-wont-compile-on-windows-7-x64).

**Comment by orchidas** [comment]
Thanks so much. So MinGW-64 just does not work. I downloaded MS Visual Studio for Python 2.7 from [this](https://www.microsoft.com/en-us/download/details.aspx?id=44266) link. Then, I had to use 
`python setup.py build_ext --inplace --compiler=msvc
python setup.py install`
That worked because it compiled .c to .pyd instead of .o (I think). So now I have resampy, and hence librosa! Thanks for your support.

**Comment by bmcfee** [comment]
Great, glad it's working now!

I'll close this one out after merging #23.

**Comment by petergh1** [comment]
Problem trying to use Resampy solution #22
This is the solution supplied by #22:
Thanks so much. So MinGW-64 just does not work. I downloaded MS Visual Studio for Python 2.7 from thislink. Then, I had to use
python setup.py build_ext --inplace --compiler=msvc python setup.py install

These are my questions
I have the same problem and have been trying to use the mentioned solution and have the following questions. BTW, I am a novice at Python.
- I am using Python 3.5.3 so should I download Microsot Visual C++ Compiler package for Python 3.5 or will 2.7 as per solution be ok?
- Could you please advise how to run the scripts mentioned in the solution. What current directory and path should I use. Should I use a terminal session or something else?
- If you could guide me step by step then I would really appreciate it.
Thanks.
Peter
