### ISSUE TITLE
Don't know how to compile resampy/interp.pyx

### ISSUE THREAD

**Issue by josephernest** [bmcfee/resampy#26]
Hi! `pip install resampy` gives me:

    building 'resampy.interp' extension
    error: Don't know how to compile resampy/interp.pyx

The problem is that I can't get `librosa` installed anymore because librosa needs resampy...

**Comment by bmcfee** [comment]
This is probably redundant with #24 ; and is a known issue that I'll fix in the next few days when I'm somewhere with stable wifi.

Meanwhile: have you tried cloning and pip installing as described in #25 ?

**Comment by bmcfee** [comment]
@josephernest can you try installing 0.1.4rc1 (on pypi) and let me know if it works?

Thanks.

**Comment by bmcfee** [comment]
Closed by merging #29
