### ISSUE TITLE
0.1.4rc breaks my CI

### ISSUE THREAD

**Issue by jorgehatccrma** [bmcfee/resampy#30]
20 hours ago my continuous integration started to fail with this error:

```
Installed xxxxx/builds/ccbf14cd/0/algorithm/tools/.eggs/librosa-0.4.3-py2.7.egg
Searching for resampy>=0.1.0
Reading https://pypi.python.org/simple/resampy/
Best match: resampy 0.1.4rc0
Downloading https://pypi.python.org/packages/e9/93/da2deb7137fd12b679dfb8e20548b270b9602e03bc970d977134aa2d37bb/resampy-0.1.4rc0.tar.gz#md5=d584ea138ea085d83ea134992ca56607
Processing resampy-0.1.4rc0.tar.gz
Writing /var/folders/gg/zxfl0y1519q5p8g5vnbb6q980000gn/T/easy_install-qJ0PtN/resampy-0.1.4rc0/setup.cfg
Running resampy-0.1.4rc0/setup.py -q bdist_egg --dist-dir /var/folders/gg/zxfl0y1519q5p8g5vnbb6q980000gn/T/easy_install-qJ0PtN/resampy-0.1.4rc0/egg-dist-tmp-bl1P9J
Compiling resampy/interp.pyx because it depends on /usr/local/lib/python2.7/site-packages/Cython/Includes/numpy/__init__.pxd.
[1/1] Cythonizing resampy/interp.pyx
warning: no files found matching '*.pxd' under directory 'resampy'
resampy/interp.c:280:10: fatal error: 'numpy/arrayobject.h' file not found
#include "numpy/arrayobject.h"
         ^
1 error generated.
error: Setup script exited with error: command 'clang' failed with exit status 1
```

This was the first build I attempted after your ac447c5a0c3ae13be316bd012c83056ecd128a61 commit, 22 hours ago. That seems to be the culprit.

I'm not explicitly importing/using resampy, but I guess it is a dependency for librosa. 

As a temporary solution for me, I forced it to use resampy==0.1.3 and my CI builds without errors. But that's obviously not the ideal solution.

**Comment by bmcfee** [comment]
Thanks for reporting this -- that's exactly why it's a release candidate!

For CI purposes, you can fix it with an explicit version (`pip install resampy==0.1.3`) until I get a new rc up.

**Comment by bmcfee** [comment]
@jorgehatccrma btw, could you list your build environment (python dist, package versions, etc)?

**Comment by jorgehatccrma** [comment]
My build environment:

- OS X 10.11
- homebrewed python 2.7.11
- package versions:
    - appnope (0.1.0)
    - BeautifulSoup (3.2.1)
    - boto (2.39.0)
    - click (6.6)
    - coverage (4.0.3)
    - cycler (0.9.0)
    - Cython (0.24)
    - decorator (4.0.6)
    - Flask (0.11.1)
    - gevent (1.1.1)
    - gnureadline (6.3.3)
    - greenlet (0.4.9)
    - ipython (4.0.2)
    - ipython-genutils (0.1.0)
    - itsdangerous (0.24)
    - Jinja2 (2.8)
    - kik (1.0.7)
    - madmom (0.14.dev0)
    - MarkupSafe (0.23)
    - matplotlib (1.5.1)
    - nltk (3.1)
    - numpy (1.10.4)
    - pandas (0.17.1)
    - path.py (8.1.2)
    - pexpect (4.0.1)
    - pickleshare (0.5)
    - Pillow (3.2.0)
    - pip (8.1.2)
    - psycopg2 (2.6.1)
    - ptyprocess (0.5)
    - py (1.4.31)
    - pyparsing (2.1.0)
    - pytest (2.9.1)
    - pytest-cov (2.2.1)
    - python-dateutil (2.4.2)
    - pytz (2015.7)
    - redis (2.10.5)
    - requests (2.9.1)
    - scipy (0.17.0)
    - seaborn (0.7.0)
    - setuptools (20.4)
    - simplegeneric (0.8.1)
    - six (1.10.0)
    - slacker (0.9.15)
    - spotipy (2.3.8)
    - tqdm (3.8.0)
    - traitlets (4.1.0)
    - Unidecode (0.4.18)
    - vboxapi (1.0)
    - websocket (0.2.1)
    - websocket-client (0.37.0)
    - Werkzeug (0.11.10)
    - wheel (0.26.0)

**Comment by bmcfee** [comment]
This seems like another instance of [this issue](https://github.com/hmmlearn/hmmlearn/issues/43); setup on osx seems to not pass the `include_dir` variable.  (Strangely, on my linux install, it *only* worked if I pass that variable.)

You can work around this by explicitly setting CFLAGS in the environment to include your numpy path (see [here](https://github.com/hmmlearn/hmmlearn/issues/43#issuecomment-130426976)); I'll try to find a more sane fix.

**Comment by bmcfee** [comment]
0.1.4rc1 is up; please let me know if it's still breaking for you.

**Comment by bmcfee** [comment]
@jorgehatccrma can you please give the current pre-release a spin and let me know if it fixes your issue?

Thanks.

**Comment by jorgehatccrma** [comment]
I'm in vacations with my family, trying to avoid computer time. Will look
into it next week.

**Comment by bmcfee** [comment]
Okay, no problem. Thanks for the response!

**Comment by carlthome** [comment]
Same problem for me with:

```
conda skeleton pypi resampy
conda build resampy
```

Currently reverted to 0.1.3.

**Comment by bmcfee** [comment]
Okay, @carlthome 0.1.4rc3 should fix this for sure.  The skeleton build now works for me.  Please confirm?

**Comment by carlthome** [comment]
Yup, working now. :+1:

**Comment by bmcfee** [comment]
Okay.  I'm closing this one now that I understand what's going on.  :shipit:
