### ISSUE TITLE
[JOSS review] Contribution guidelines

### ISSUE THREAD

**Issue by arokem** [bmcfee/resampy#39]
"Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support" 

Seems to me that item 2 is covered through the link to the issue tracker, but it would be good to (at the very least) add a `CONTRIBUTING` file to the repo (see: https://github.com/blog/1184-contributing-guidelines).

**Comment by bmcfee** [comment]
Fixed by merging #42
