### ISSUE TITLE
[JOSS Review] References require a DOI

### ISSUE THREAD

**Issue by arokem** [bmcfee/resampy#40]
Required by JOSS review criteria:

"Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?"

**Comment by bmcfee** [comment]
Are you referring to the package itself (eg zenodo DOI), or the source material reference (Smith) in the docs?

For the latter: he explicitly requests a specific form of citation to his web book, which does not currently have a DOI.  Any advice about how to handle that?

**Comment by arokem** [comment]
I guess there's not much to do about the web-book (except maybe to ask the author to DOI it, if only so that it's available when he retires, or when his group's website is migrated...). Does the software referenced have a DOI?

**Comment by bmcfee** [comment]
Yes, there's a zenodo DOI.  The badge is in the updated readme in #42 .

**Comment by arokem** [comment]
To be clear -- this reference: 

https://github.com/bmcfee/resampy/blob/master/paper/paper.bib#L9

still requires a DOI, if such exists

**Comment by bmcfee** [comment]
libsamplerate also does not appear to have a DOI.

**Comment by arokem** [comment]
OK. I guess that's not too important, because who would use that, now that
they have resampy? :-)

Closing.
