### ISSUE TITLE
Type-check and raise exception for unsupported input formats (int, complex, etc)

### ISSUE THREAD

**Issue by SamyCookie** [bmcfee/resampy#44]
Hi,

I tried to find a Python resampling tool faster than scipy.resample, and I think that you're project is a nice solution, thanks for that ;)

But, after install it via pip, and when I test it, I got :
```
Traceback (most recent call last): [...]
    samples = resample(audio[offset:offset + n], sample_rate, 32000)
  File "/usr/local/lib/python2.7/dist-packages/resampy/core.py", line 109, in resample
    resample_f(x_2d, y_2d, sample_ratio, interp_win, interp_delta, precision)
  File "resampy/interp.pyx", line 15, in resampy.interp.__pyx_fused_cpdef (resampy/interp.c:2921)
TypeError: No matching signature found
```

This issue appears on a Debian jessie 64bits machine, thanks for future help !

**Comment by bmcfee** [comment]
It looks like your `audio` buffer has a dtype that resampy can't handle.  For a little background, resample is implemented in cython using fused float types, so it should be able to handle any (real) floating-point representation of input.  It will not work on integer or complex types.

Can you do:
```python
>>> print audio.dtype, type(sample_rate)
```
and report the result?

**Comment by SamyCookie** [comment]
No need to test, I knew that my samples are in PCM int16 :/
I have translated to float32 and all is fine.

However, i think that this information is missing in the doc and should be present:
```
Parameters:	
x : np.ndarray
    The input signal(s) to resample
```
And another note, I think it should be reasonnable to test the input and fail with a comprehensive exception if this input is wrong.

Anyway thanks for the help, I can now test your tool !
Have a goold day.

**Comment by bmcfee** [comment]
Thanks for verifying my suspicion!

> And another note, I think it should be reasonnable to test the input and fail with a comprehensive exception if this input is wrong.

Agreed.  I'm reopening this issue so that we can keep track of it until the documentation / exception handling is properly updated.

**Comment by kylerbrown** [comment]
Hey @bmcfee All my data are int16 arrays, had I not found this issue, I would have had no idea what to do. A helpful error would be greatly appreciated.
(oh and thanks for the library! Makes my life easier. :sunglasses: )
