### ISSUE TITLE
Issue when installing

### ISSUE THREAD

**Issue by adybady** [bmcfee/resampy#50]
C:\Windows\system32>pip install resampy
Collecting resampy
  Using cached resampy-0.1.5.tar.gz
Requirement already satisfied: numpy>=1.10 in c:\users\ady\appdata\local\program
s\python\python35\lib\site-packages (from resampy)
Requirement already satisfied: scipy>=0.13 in c:\users\ady\appdata\local\program
s\python\python35\lib\site-packages (from resampy)
Requirement already satisfied: six>=1.3 in c:\users\ady\appdata\local\programs\p
ython\python35\lib\site-packages (from resampy)
Requirement already satisfied: Cython>=0.23 in c:\users\ady\appdata\local\progra
ms\python\python35\lib\site-packages (from resampy)
Building wheels for collected packages: resampy
  Running setup.py bdist_wheel for resampy ... error
  Complete output from command c:\users\ady\appdata\local\programs\python\python
35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ady\\AppDa
ta\\Local\\Temp\\pip-build-ak_l9n7g\\resampy\\setup.py';f=getattr(tokenize, 'ope
n', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(c
ode, __file__, 'exec'))" bdist_wheel -d C:\Users\Ady\AppData\Local\Temp\tmpx9udi
l_epip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.5
  creating build\lib.win-amd64-3.5\resampy
  copying resampy\core.py -> build\lib.win-amd64-3.5\resampy
  copying resampy\filters.py -> build\lib.win-amd64-3.5\resampy
  copying resampy\version.py -> build\lib.win-amd64-3.5\resampy
  copying resampy\__init__.py -> build\lib.win-amd64-3.5\resampy
  creating build\lib.win-amd64-3.5\resampy\data
  copying resampy\data\kaiser_best.npz -> build\lib.win-amd64-3.5\resampy\data
  copying resampy\data\kaiser_fast.npz -> build\lib.win-amd64-3.5\resampy\data
  running build_ext
  building 'resampy.interp' extension
  error: [WinError 3] The system cannot find the path specified: 'C:\\Program Fi
les (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib'

  ----------------------------------------
  Failed building wheel for resampy
  Running setup.py clean for resampy
Failed to build resampy
Installing collected packages: resampy
  Running setup.py install for resampy ... error
    Complete output from command c:\users\ady\appdata\local\programs\python\pyth
on35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ady\\App
Data\\Local\\Temp\\pip-build-ak_l9n7g\\resampy\\setup.py';f=getattr(tokenize, 'o
pen', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile
(code, __file__, 'exec'))" install --record C:\Users\Ady\AppData\Local\Temp\pip-
a625b11n-record\install-record.txt --single-version-externally-managed --compile
:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\resampy
    copying resampy\core.py -> build\lib.win-amd64-3.5\resampy
    copying resampy\filters.py -> build\lib.win-amd64-3.5\resampy
    copying resampy\version.py -> build\lib.win-amd64-3.5\resampy
    copying resampy\__init__.py -> build\lib.win-amd64-3.5\resampy
    creating build\lib.win-amd64-3.5\resampy\data
    copying resampy\data\kaiser_best.npz -> build\lib.win-amd64-3.5\resampy\data

    copying resampy\data\kaiser_fast.npz -> build\lib.win-amd64-3.5\resampy\data

    running build_ext
    building 'resampy.interp' extension
    error: [WinError 3] The system cannot find the path specified: 'C:\\Program
Files (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib'

    ----------------------------------------
Command "c:\users\ady\appdata\local\programs\python\python35\python.exe -u -c "i
mport setuptools, tokenize;__file__='C:\\Users\\Ady\\AppData\\Local\\Temp\\pip-b
uild-ak_l9n7g\\resampy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);co
de=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec')
)" install --record C:\Users\Ady\AppData\Local\Temp\pip-a625b11n-record\install-
record.txt --single-version-externally-managed --compile" failed with error code
 1 in C:\Users\Ady\AppData\Local\Temp\pip-build-ak_l9n7g\resampy\

**Comment by bmcfee** [comment]
It looks to me like this problem results from not having a C compiler?  Does the discussion thread in https://github.com/bmcfee/resampy/issues/22 resolve your problem?

**Comment by adybady** [comment]
Hello!
Thank you for your help and sorry for the late answer.
I made some progress..I had C compiler, but there was not in the environment variables.
I also made another new environment variable, named INCLUDE , to io.h, because it's made an error.
In my computer there was in 
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\
There is a new error now:
```
C:\resampy-master>python setup.py build_ext --inplace --compiler=msvc
running build_ext
building 'resampy.interp' extension
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe /c /nologo /Ox
 /W3 /GL /DNDEBUG /MD -DCYTHON_TRACE_NOGIL=1 -IC:\Users\Ady\AppData\Local\Progra
ms\Python\Python35\lib\site-packages\numpy\core\include -IC:\Users\Ady\AppData\L
ocal\Programs\Python\Python35\include -IC:\Users\Ady\AppData\Local\Programs\Pyth
on\Python35\include "-IC:\Program Files (x86)\Windows Kits\10\Include\10.0.10150
.0\ucrt\" /Tcresampy/interp.c /Fobuild\temp.win-amd64-3.5\Release\resampy/interp
.obj
cl : Command line error D8003 : missing source filename
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\
cl.exe' failed with exit status 2
```

**Comment by bmcfee** [comment]
I'm closing this one out, since the 0.2.0 release is now up and should fix this problem.  Please re-open if the problem persists.

**Comment by joseortiz3** [comment]
Just wanted to say this error "cannot find Microsoft Visual Studio 14.0\VC\PlatformSDK\lib" comes up when you don't have Windows SDK installed.
