### ISSUE TITLE
how to implement resampy for live microphone

### ISSUE THREAD

**Issue by saibharani** [bmcfee/resampy#52]
I want to convert sample rate of live microphone from pyaudio at 44100hz to 16000hz and use it with pocketsphinx can anyone please help to convert samplerate of live recording with resampy.
Thank you

**Comment by tgarc** [comment]
I have effectively the same question: how could you resample in an iterative fashion such that you could resample signals that are larger than the available system memory?

**Comment by bmcfee** [comment]
In principle, you could do this by buffering your large signal into overlapping windows, resampling the windows, and then overlap-adding the results.  None of this should be conceptually difficult to do -- the stride between windows can be set to match the length of the interpolation filter -- but it would take a little bit of care to do efficiently and without distortion.

If anyone is serious about implementing this, it would be great to have.  I won't have the time to do it myself for the near future though.

**Comment by bmcfee** [comment]
Closing this out - see #67 for a bit more discussion on the topic.
