### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by szvsw** [bmcfee/resampy#72]
![image](https://user-images.githubusercontent.com/36545842/72211475-fac3d480-3499-11ea-9aa7-98b3308fd08c.png)

I had an issue trying to import Librosa, so I want through the requirements for it one by one and found that `resampy` seemed to be causing the error.  I'm attaching a screen shot of the issue.  

Any ideas?  My goal is to use Librosa to reproduce the technique outlined in the recent voice anonymization publication, which seems like it should be straightforward but I have to get librosa importing fine first!

**Comment by bmcfee** [comment]
I think the problem is coming from numba, which resampy uses for jit compilation/acceleration. Are you able to import and use numba?

As a general side note: I recommend using a conda environment rather than pip, if that's an option for you.
