### ISSUE TITLE
Question : is it possible to apply fractional delay?

### ISSUE THREAD

**Issue by pfeatherstone** [bmcfee/resampy#74]
Can one use resampy to apply a fractional delay to the audio, say sqrt(2) of a sample?

**Comment by bmcfee** [comment]
If you just want a delay, and not a change of sampling rate, resampy is not the right tool for this.

**Comment by pfeatherstone** [comment]
Okidok. Can I suggest adding a delay parameter to your FIR filters? This is trivially done for sinc functions, not so trivial for window functions, but still ok.

**Comment by bmcfee** [comment]
What would be the use case for this?  It's easy enough to implement a delay before (or after) resampling, so I'm not seeing much benefit in combining the two and making the resampling implementation more complex.

**Comment by pfeatherstone** [comment]
Sorry, I guess it wouldn't be part of a resampling operation. Just some FIR filtering. Since resampling requires doing some filtering anyway, maybe expose some filtering functions. The use case is if i want to apply some fractional delay to the audio.

**Comment by bmcfee** [comment]
Right -- if it's not part of resampling, it should be a different API.
